return Def.ActorFrame {
	OnCommand=function(self)
		self:sleep(8):queuecommand("Transition")
	end,
	TransitionCommand=function(self)
		SCREENMAN:GetTopScreen():StartTransitioningScreen("SM_GoToNextScreen")
	end,
	Def.Sprite{
		Texture=THEME:GetPathG("Intro","Credits/Team.png"),
        OnCommand=function(self)
			self:zoom(0.25)
				:xy(SCREEN_CENTER_X-30,SCREEN_CENTER_Y-400)
				:sleep(1)
				:linear(0.1)
				:addy(370)
				:linear(0.05)
				:addy(-5)
				:linear(0.05)
				:addy(5)
				:sleep(2)
				:linear(0.5)
				:diffusealpha(0)
		end
	},
	Def.Sprite{
		Texture=THEME:GetPathG("Intro","Credits/Sushi.png"),
		OnCommand=function(self)
			self:zoom(0.25)
				:xy(SCREEN_CENTER_X+30,SCREEN_CENTER_Y+400)
				:sleep(1)
				:linear(0.1)
				:addy(-370)
				:linear(0.05)
				:addy(5)
				:linear(0.05)
				:addy(-5)
				:sleep(2)
				:linear(0.5)
				:diffusealpha(0)
		end
	},
	Def.Sprite{
		Texture=THEME:GetPathG("Intro","Credits/RhythmLunatic.png"),
        OnCommand=function(self)
			self:zoom(0.25)
				:xy(SCREEN_CENTER_X+800,SCREEN_CENTER_Y)
				:sleep(4)
				:linear(0.1)
				:addx(-800)
				:linear(0.05)
				:addx(5)
				:linear(0.05)
				:addx(-5)
				:sleep(2)
				:linear(0.5)
				:diffusealpha(0)
		end
	}
}
