return Def.ActorFrame{
	Def.Sprite{
		Texture=THEME:GetPathG("","chibi/yuri"),
		Condition=(not GAMESTATE:IsExtraStage() and not GAMESTATE:IsExtraStage2()),
		StartTransitioningCommand=function(self)
			self:finishtweening()
				:y(SCREEN_BOTTOM+150)
				:x(SCREEN_CENTER_X+60)
				:zoom(0.6)
				:animate(false)
				:setstate(1)
				:bounce()
				:effectmagnitude(0,-30,0)
				:effectperiod(0.25)
				:linear(0.1)
				:y(SCREEN_BOTTOM-50)
				:sleep(1)
				:linear(0.1)
				:y(SCREEN_BOTTOM+150)
		end
	},
	Def.Sprite{
		Texture=THEME:GetPathG("","chibi/natsuki"),
		Condition=(not GAMESTATE:IsExtraStage() and not GAMESTATE:IsExtraStage2()),
		StartTransitioningCommand=function(self)
			self:finishtweening()
				:y(SCREEN_BOTTOM+150)
				:x(SCREEN_CENTER_X-60)
				:zoom(0.6)
				:animate(false)
				:setstate(1)
				:bounce()
				:effectmagnitude(0,-30,0)
				:effectperiod(0.25)
				:linear(.1)
				:y(SCREEN_BOTTOM-50)
				:sleep(1)
				:linear(.1)
				:y(SCREEN_BOTTOM+150)
		end
	},
	Def.Sprite{
		Texture=THEME:GetPathG("","chibi/sayori"),
		Condition=(not GAMESTATE:IsExtraStage()),
		StartTransitioningCommand=function(self)
			self:finishtweening()
				:y(SCREEN_BOTTOM+150)
				:x(SCREEN_CENTER_X-180)
				:zoom(0.6)
				:animate(false)
				:setstate(1)
				:bounce()
				:effectmagnitude(0,-30,0)
				:effectperiod(0.25)
				:linear(.1)
				:y(SCREEN_BOTTOM-50)
				:sleep(1)
				:linear(.1)
				:y(SCREEN_BOTTOM+150)
		end
	},
	Def.Sprite{
		Texture=THEME:GetPathG("","chibi/monika"),
		Condition=(not GAMESTATE:IsExtraStage2()),
		StartTransitioningCommand=function(self)
			self:finishtweening()
				:y(SCREEN_BOTTOM+150)
				:x(SCREEN_CENTER_X+180)
				:zoom(0.6)
				:animate(false)
				:setstate(1)
				:bounce()
				:effectmagnitude(0,-30,0)
				:effectperiod(0.25)
				:linear(.1)
				:y(SCREEN_BOTTOM-50)
				:sleep(1)
				:linear(.1)
				:y(SCREEN_BOTTOM+150)
		end
	},
	Def.BitmapText{
		Text="COMBO STREAK REACHED!",
		Font="_riffic free medium 40px",
		StartTransitioningCommand=function(self)
			self:finishtweening()
				:y(SCREEN_CENTER_Y)
				:x(SCREEN_CENTER_X)
				:diffusealpha(0)
				:zoom(0.6)
				:strokecolor(color("#fe81ae"))
				:linear(.1)
				:diffusealpha(1)
				:sleep(1)
				:linear(.1)
				:diffusealpha(0)
		end
	},
}
