return Def.ActorFrame {
	OnCommand=function(self)
		self:sleep(4):queuecommand("Transition")
	end,
	TransitionCommand=function(self)
		SCREENMAN:GetTopScreen():StartTransitioningScreen("SM_GoToNextScreen")
	end,
	Def.Sprite{
		Texture=THEME:GetPathG("Team","Sushi/Team.png"),
        OnCommand=function(self)
			self:zoom(0.25)
				:xy(SCREEN_CENTER_X-30,SCREEN_CENTER_Y-400)
				:sleep(1)
				:linear(0.1)
				:addy(370)
				:sleep(0.05)
				:addy(-1)
				:sleep(0.05)
				:addy(1)
				:sleep(2)
				:linear(0.5)
				:diffusealpha(0)
		end
	},
	Def.Sprite{
		Texture=THEME:GetPathG("Team","Sushi/Sushi.png"),
		OnCommand=function(self)
			self:zoom(0.25)
				:xy(SCREEN_CENTER_X+30,SCREEN_CENTER_Y+400)
				:sleep(1)
				:linear(0.1)
				:addy(-370)
				:sleep(0.05)
				:addy(1)
				:sleep(0.05)
				:addy(-1)
				:sleep(2)
				:linear(0.5)
				:diffusealpha(0)
		end
	}
}
